package scanner

import "testing"

func TestParseRequirements(t *testing.T) {
	path := writeTempFile(t, "requirements.txt", `# comment
requests[security]==2.31.0 # inline comment
Django>=4.2
-r base.txt
git+https://example.com/repo.git
flask==3.0.0,<4
wild==1.2.*
`)

	pkgs, err := parseRequirements(path)
	if err != nil {
		t.Fatalf("parseRequirements returned error: %v", err)
	}
	if len(pkgs) != 4 {
		t.Fatalf("expected 4 packages, got %d: %#v", len(pkgs), pkgs)
	}
	cases := map[string]string{
		"requests": "2.31.0",
		"Django":   "",
		"flask":    "3.0.0",
		"wild":     "1.2",
	}
	for name, version := range cases {
		pkg, ok := packageByName(pkgs, name)
		if !ok {
			t.Fatalf("package %s not found: %#v", name, pkgs)
		}
		if pkg.Version != version || pkg.Ecosystem != "python" {
			t.Fatalf("unexpected package for %s: %#v", name, pkg)
		}
	}
}

func TestParsePipfileLockIncludesDefaultAndDevelop(t *testing.T) {
	path := writeTempFile(t, "Pipfile.lock", `{
  "default": {
    "requests": { "version": "==2.31.0" }
  },
  "develop": {
    "pytest": { "version": "==8.1.1" }
  }
}`)

	pkgs, err := parsePipfileLock(path)
	if err != nil {
		t.Fatalf("parsePipfileLock returned error: %v", err)
	}
	if len(pkgs) != 2 {
		t.Fatalf("expected 2 packages, got %d: %#v", len(pkgs), pkgs)
	}
	for name, version := range map[string]string{"requests": "2.31.0", "pytest": "8.1.1"} {
		pkg, ok := packageByName(pkgs, name)
		if !ok {
			t.Fatalf("package %s not found: %#v", name, pkgs)
		}
		if pkg.Version != version || pkg.Ecosystem != "python" {
			t.Fatalf("unexpected package for %s: %#v", name, pkg)
		}
	}
}

func TestParsePoetryLock(t *testing.T) {
	path := writeTempFile(t, "poetry.lock", `# generated by Poetry

[[package]]
name = "requests"
version = "2.31.0"
description = "HTTP library"

[[package]]
name = "urllib3"
version = "2.0.7"
`)

	pkgs, err := parsePoetryLock(path)
	if err != nil {
		t.Fatalf("parsePoetryLock returned error: %v", err)
	}
	if len(pkgs) != 2 {
		t.Fatalf("expected 2 packages, got %d: %#v", len(pkgs), pkgs)
	}
	urllib3, ok := packageByName(pkgs, "urllib3")
	if !ok || urllib3.Version != "2.0.7" || urllib3.Ecosystem != "python" {
		t.Fatalf("unexpected urllib3 package: %#v found=%v", urllib3, ok)
	}
}
